on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  verbose-info:
    runs-on: ubuntu-latest
    steps:
    - name: Verbose Info
      id: verbose
      uses: 52-entertainment/verbose-action-info@main
    - run: echo Verbose event string ${{ steps.verbose.outputs.event }}
    - run: echo Run URL ${{ steps.verbose.outputs.run_url }}
    - run: echo Event name ${{ steps.verbose.outputs.name }}
    - run: echo Pull request number ${{ steps.verbose.outputs.pr_url }}
    - run: echo PR URL ${{ steps.verbose.outputs.pr_url }}
    - run: echo Short commit hash ${{ steps.verbose.outputs.sha }}
    - run: echo Commit URL ${{ steps.verbose.outputs.commit_url }}
    - run: echo Ref URL ${{ steps.verbose.outputs.ref_url }}
    - run: echo Ref ${{ steps.verbose.outputs.ref }}
    - run: echo Ref type ${{ steps.verbose.outputs.ref_type }}
